FROM maven:3.9.6-eclipse-temurin-21 AS build
LABEL authors="Sofie"
WORKDIR /usr/local/knitulator
COPY pom.xml .
COPY src src

RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jdk-jammy
WORKDIR /app

copy --from=build /usr/local/knitulator/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.jar"]