/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyPatternsRouteImport } from './routes/my-patterns'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatternsHatsInputRouteImport } from './routes/patterns.hats-input'
import { Route as PatternsIdRouteImport } from './routes/patterns.$id'
import { Route as CategoryTypeRouteImport } from './routes/category.$type'
import { Route as CreateTypePatternRouteImport } from './routes/create.$type.$pattern'

const MyPatternsRoute = MyPatternsRouteImport.update({
  id: '/my-patterns',
  path: '/my-patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsHatsInputRoute = PatternsHatsInputRouteImport.update({
  id: '/patterns/hats-input',
  path: '/patterns/hats-input',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsIdRoute = PatternsIdRouteImport.update({
  id: '/patterns/$id',
  path: '/patterns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryTypeRoute = CategoryTypeRouteImport.update({
  id: '/category/$type',
  path: '/category/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTypePatternRoute = CreateTypePatternRouteImport.update({
  id: '/create/$type/$pattern',
  path: '/create/$type/$pattern',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-patterns': typeof MyPatternsRoute
  '/category/$type': typeof CategoryTypeRoute
  '/patterns/$id': typeof PatternsIdRoute
  '/patterns/hats-input': typeof PatternsHatsInputRoute
  '/create/$type/$pattern': typeof CreateTypePatternRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-patterns': typeof MyPatternsRoute
  '/category/$type': typeof CategoryTypeRoute
  '/patterns/$id': typeof PatternsIdRoute
  '/patterns/hats-input': typeof PatternsHatsInputRoute
  '/create/$type/$pattern': typeof CreateTypePatternRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my-patterns': typeof MyPatternsRoute
  '/category/$type': typeof CategoryTypeRoute
  '/patterns/$id': typeof PatternsIdRoute
  '/patterns/hats-input': typeof PatternsHatsInputRoute
  '/create/$type/$pattern': typeof CreateTypePatternRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/my-patterns'
    | '/category/$type'
    | '/patterns/$id'
    | '/patterns/hats-input'
    | '/create/$type/$pattern'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/my-patterns'
    | '/category/$type'
    | '/patterns/$id'
    | '/patterns/hats-input'
    | '/create/$type/$pattern'
  id:
    | '__root__'
    | '/'
    | '/my-patterns'
    | '/category/$type'
    | '/patterns/$id'
    | '/patterns/hats-input'
    | '/create/$type/$pattern'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyPatternsRoute: typeof MyPatternsRoute
  CategoryTypeRoute: typeof CategoryTypeRoute
  PatternsIdRoute: typeof PatternsIdRoute
  PatternsHatsInputRoute: typeof PatternsHatsInputRoute
  CreateTypePatternRoute: typeof CreateTypePatternRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-patterns': {
      id: '/my-patterns'
      path: '/my-patterns'
      fullPath: '/my-patterns'
      preLoaderRoute: typeof MyPatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns/hats-input': {
      id: '/patterns/hats-input'
      path: '/patterns/hats-input'
      fullPath: '/patterns/hats-input'
      preLoaderRoute: typeof PatternsHatsInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns/$id': {
      id: '/patterns/$id'
      path: '/patterns/$id'
      fullPath: '/patterns/$id'
      preLoaderRoute: typeof PatternsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$type': {
      id: '/category/$type'
      path: '/category/$type'
      fullPath: '/category/$type'
      preLoaderRoute: typeof CategoryTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/$type/$pattern': {
      id: '/create/$type/$pattern'
      path: '/create/$type/$pattern'
      fullPath: '/create/$type/$pattern'
      preLoaderRoute: typeof CreateTypePatternRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyPatternsRoute: MyPatternsRoute,
  CategoryTypeRoute: CategoryTypeRoute,
  PatternsIdRoute: PatternsIdRoute,
  PatternsHatsInputRoute: PatternsHatsInputRoute,
  CreateTypePatternRoute: CreateTypePatternRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
