spring:
  application:
    name: backend
  datasource:
    url: ${DB_CONNECTION_STRING}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true
